// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package config

import (
	"erdemkayacomtr/controllers"
	"erdemkayacomtr/repositories"
	"erdemkayacomtr/services"
	"github.com/google/wire"
)

// Injectors from injector.go:

func Init() *Initialization {
	gormDB := ConnectToDB()
	categoryRepositoryImpl := repositories.CategoryRepositoryInit(gormDB)
	categoryServiceImpl := services.CategoryServiceInit(categoryRepositoryImpl)
	categoryControllerImpl := controllers.CategoryControllerInit(categoryServiceImpl)
	initialization := NewInitializer(categoryRepositoryImpl, categoryServiceImpl, categoryControllerImpl)
	return initialization
}

// injector.go:

var db = wire.NewSet(ConnectToDB)

var categoryRepositorySet = wire.NewSet(repositories.CategoryRepositoryInit, wire.Bind(new(repositories.CategoryRepository), new(*repositories.CategoryRepositoryImpl)))

var categoryServiceSet = wire.NewSet(services.CategoryServiceInit, wire.Bind(new(services.CategoryService), new(*services.CategoryServiceImpl)))

var categoryControllerSet = wire.NewSet(controllers.CategoryControllerInit, wire.Bind(new(controllers.CategoryController), new(*controllers.CategoryControllerImpl)))
